import type { OpsDataset } from "@/lib/ops/types";

export const opsMockData: OpsDataset = {
  operators: [
    { id: "op-weekly-book", name: "North Star Book", category: "sportsbook" },
    { id: "op-casino-monthly", name: "River Casino", category: "casino" },
    { id: "op-weekly-book-2", name: "Harbor Book", category: "sportsbook" },
  ],
  accounts: [
    {
      id: "acct-alpha",
      operatorId: "op-weekly-book",
      label: "Alpha 07",
      status: "active",
      openedAt: "2026-01-15T00:00:00Z",
      externalAccountRef: "alpha-07",
    },
    {
      id: "acct-bravo",
      operatorId: "op-casino-monthly",
      label: "Bravo 11",
      status: "collections",
      openedAt: "2025-11-20T00:00:00Z",
      externalAccountRef: "bravo-11",
    },
    {
      id: "acct-charlie",
      operatorId: "op-weekly-book-2",
      label: "Charlie 03",
      status: "paused",
      openedAt: "2026-03-09T00:00:00Z",
      externalAccountRef: "charlie-03",
    },
  ],
  walletEntries: [
    {
      id: "we-alpha-open",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "opening_balance",
      sourceOfEntry: "system",
      signedAmount: 5000,
      status: "posted",
      occurredAt: "2026-01-15T00:00:00Z",
      postedAt: "2026-01-15T00:00:00Z",
      description: "Opening cash balance",
    },
    {
      id: "we-alpha-dep-1",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "deposit",
      sourceOfEntry: "import",
      signedAmount: 10000,
      status: "posted",
      occurredAt: "2026-04-07T15:02:00Z",
      postedAt: "2026-04-07T15:05:00Z",
      externalRef: "dep-alpha-1001",
      dedupeKey: "acct-alpha|deposit|dep-alpha-1001|10000",
      description: "Main weekly funding deposit",
    },
    {
      id: "we-alpha-dep-dup",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "deposit",
      sourceOfEntry: "import",
      signedAmount: 10000,
      status: "duplicate",
      occurredAt: "2026-04-07T15:07:00Z",
      externalRef: "dep-alpha-1001",
      dedupeKey: "acct-alpha|deposit|dep-alpha-1001|10000",
      description: "Duplicate deposit attempt, excluded from balance",
    },
    {
      id: "we-alpha-stake-1",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "wager_stake",
      sourceOfEntry: "import",
      signedAmount: -4000,
      status: "posted",
      occurredAt: "2026-04-08T00:12:00Z",
      postedAt: "2026-04-08T00:12:00Z",
      ticketId: "tk-alpha-win",
      description: "Stake for Lakers @ Warriors",
    },
    {
      id: "we-alpha-payout-1",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "wager_payout",
      sourceOfEntry: "import",
      signedAmount: 7600,
      status: "posted",
      occurredAt: "2026-04-08T04:15:00Z",
      postedAt: "2026-04-08T04:16:00Z",
      ticketId: "tk-alpha-win",
      description: "Payout for settled winning ticket",
    },
    {
      id: "we-alpha-stake-2",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "wager_stake",
      sourceOfEntry: "import",
      signedAmount: -3500,
      status: "posted",
      occurredAt: "2026-04-17T01:55:00Z",
      postedAt: "2026-04-17T01:55:00Z",
      ticketId: "tk-alpha-open",
      description: "Open ticket still at risk",
    },
    {
      id: "we-alpha-stake-week",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "wager_stake",
      sourceOfEntry: "import",
      signedAmount: -1200,
      status: "posted",
      occurredAt: "2026-04-15T01:10:00Z",
      postedAt: "2026-04-15T01:10:00Z",
      ticketId: "tk-alpha-week",
      description: "Current-week settled ticket stake",
    },
    {
      id: "we-alpha-payout-week",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "wager_payout",
      sourceOfEntry: "import",
      signedAmount: 2220,
      status: "posted",
      occurredAt: "2026-04-15T04:45:00Z",
      postedAt: "2026-04-15T04:45:00Z",
      ticketId: "tk-alpha-week",
      description: "Current-week settled ticket payout",
    },
    {
      id: "we-alpha-withdrawal-1",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "withdrawal",
      sourceOfEntry: "import",
      signedAmount: -3000,
      status: "posted",
      occurredAt: "2026-04-11T14:00:00Z",
      postedAt: "2026-04-11T14:05:00Z",
      externalRef: "wd-alpha-2001",
      description: "Cash sweep from account",
    },
    {
      id: "we-alpha-adjustment-1",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "manual_adjustment",
      sourceOfEntry: "manual",
      signedAmount: 250,
      status: "posted",
      occurredAt: "2026-04-12T17:30:00Z",
      postedAt: "2026-04-12T17:30:00Z",
      noteId: "note-alpha-adjustment",
      description: "Manual correction after statement mismatch",
    },
    {
      id: "we-alpha-payout-cash",
      accountId: "acct-alpha",
      walletType: "cash",
      entryType: "payout_cash_receipt",
      sourceOfEntry: "import",
      signedAmount: 900,
      status: "posted",
      occurredAt: "2026-04-10T18:20:00Z",
      postedAt: "2026-04-10T18:20:00Z",
      statementId: "stmt-alpha-prev",
      description: "Partial weekly payout received",
    },
    {
      id: "we-bravo-open-cash",
      accountId: "acct-bravo",
      walletType: "cash",
      entryType: "opening_balance",
      sourceOfEntry: "system",
      signedAmount: 2000,
      status: "posted",
      occurredAt: "2025-11-20T00:00:00Z",
      postedAt: "2025-11-20T00:00:00Z",
      description: "Opening cash balance",
    },
    {
      id: "we-bravo-open-credit",
      accountId: "acct-bravo",
      walletType: "credit",
      entryType: "opening_balance",
      sourceOfEntry: "system",
      signedAmount: 0,
      status: "posted",
      occurredAt: "2025-11-20T00:00:00Z",
      postedAt: "2025-11-20T00:00:00Z",
      description: "Opening credit balance",
    },
    {
      id: "we-bravo-dep-1",
      accountId: "acct-bravo",
      walletType: "cash",
      entryType: "deposit",
      sourceOfEntry: "import",
      signedAmount: 5000,
      status: "posted",
      occurredAt: "2026-03-29T16:00:00Z",
      postedAt: "2026-03-29T16:02:00Z",
      externalRef: "dep-bravo-3001",
      description: "Monthly reload deposit",
    },
    {
      id: "we-bravo-credit-issue-1",
      accountId: "acct-bravo",
      walletType: "credit",
      entryType: "payout_credit_receipt",
      sourceOfEntry: "import",
      signedAmount: 400,
      status: "posted",
      occurredAt: "2026-04-05T12:00:00Z",
      postedAt: "2026-04-05T12:00:00Z",
      statementId: "stmt-bravo-mar-v2",
      description: "Partial credit payout received",
    },
    {
      id: "we-bravo-credit-stake-1",
      accountId: "acct-bravo",
      walletType: "credit",
      entryType: "wager_stake",
      sourceOfEntry: "import",
      signedAmount: -800,
      status: "posted",
      occurredAt: "2026-04-06T02:30:00Z",
      postedAt: "2026-04-06T02:30:00Z",
      ticketId: "tk-bravo-credit",
      description: "Free-play ticket stake",
    },
    {
      id: "we-bravo-payout-1",
      accountId: "acct-bravo",
      walletType: "cash",
      entryType: "wager_payout",
      sourceOfEntry: "import",
      signedAmount: 600,
      status: "posted",
      occurredAt: "2026-04-06T05:40:00Z",
      postedAt: "2026-04-06T05:40:00Z",
      ticketId: "tk-bravo-credit",
      description: "Cash return from free-play ticket",
    },
    {
      id: "we-bravo-payout-cash-1",
      accountId: "acct-bravo",
      walletType: "cash",
      entryType: "payout_cash_receipt",
      sourceOfEntry: "import",
      signedAmount: 1000,
      status: "posted",
      occurredAt: "2026-04-05T12:05:00Z",
      postedAt: "2026-04-05T12:05:00Z",
      statementId: "stmt-bravo-mar-v2",
      description: "Partial cash payout received",
    },
    {
      id: "we-bravo-credit-issue-2",
      accountId: "acct-bravo",
      walletType: "credit",
      entryType: "credit_issue",
      sourceOfEntry: "system",
      signedAmount: 1200,
      status: "posted",
      occurredAt: "2026-04-01T12:00:00Z",
      postedAt: "2026-04-01T12:00:00Z",
      description: "Promotional credit granted at period open",
    },
    {
      id: "we-bravo-adjustment-disputed",
      accountId: "acct-bravo",
      walletType: "cash",
      entryType: "manual_adjustment",
      sourceOfEntry: "manual",
      signedAmount: -150,
      status: "disputed",
      occurredAt: "2026-04-07T09:15:00Z",
      noteId: "note-bravo-dispute",
      description: "Disputed manual deduction",
    },
    {
      id: "we-charlie-dep-pending",
      accountId: "acct-charlie",
      walletType: "cash",
      entryType: "deposit",
      sourceOfEntry: "import",
      signedAmount: 4000,
      status: "pending",
      occurredAt: "2026-04-15T17:45:00Z",
      externalRef: "dep-charlie-5001",
      description: "Pending deposit awaiting confirmation",
    },
    {
      id: "we-charlie-stake-open",
      accountId: "acct-charlie",
      walletType: "cash",
      entryType: "wager_stake",
      sourceOfEntry: "import",
      signedAmount: -2500,
      status: "posted",
      occurredAt: "2026-04-16T01:10:00Z",
      postedAt: "2026-04-16T01:10:00Z",
      ticketId: "tk-charlie-late",
      description: "Ticket with event final but no settlement",
    },
    {
      id: "we-charlie-withdrawal-1",
      accountId: "acct-charlie",
      walletType: "cash",
      entryType: "withdrawal",
      sourceOfEntry: "import",
      signedAmount: -1500,
      status: "posted",
      occurredAt: "2026-04-12T13:05:00Z",
      postedAt: "2026-04-12T13:06:00Z",
      externalRef: "wd-charlie-9001",
      description: "Withdrawal with no linked collections note",
    },
  ],
  marketEvents: [
    {
      id: "evt-lakers-warriors",
      sport: "NBA",
      eventName: "Lakers @ Warriors",
      startsAt: "2026-04-08T00:00:00Z",
      status: "final",
    },
    {
      id: "evt-clippers-suns",
      sport: "NBA",
      eventName: "Clippers @ Suns",
      startsAt: "2026-04-17T02:00:00Z",
      status: "live",
    },
    {
      id: "evt-orioles-yankees",
      sport: "MLB",
      eventName: "Orioles @ Yankees",
      startsAt: "2026-04-16T23:10:00Z",
      status: "final",
    },
    {
      id: "evt-celtics-heat",
      sport: "NBA",
      eventName: "Celtics @ Heat",
      startsAt: "2026-04-15T00:30:00Z",
      status: "final",
    },
  ],
  tickets: [
    {
      id: "tk-alpha-win",
      accountId: "acct-alpha",
      marketEventId: "evt-lakers-warriors",
      ticketRef: "alpha-win-1",
      market: "Moneyline",
      side: "Warriors ML",
      oddsDecimal: 1.9,
      stakeCash: 4000,
      stakeCredit: 0,
      placedAt: "2026-04-08T00:10:00Z",
      acceptedAt: "2026-04-08T00:12:00Z",
      status: "settled",
    },
    {
      id: "tk-alpha-open",
      accountId: "acct-alpha",
      marketEventId: "evt-clippers-suns",
      ticketRef: "alpha-open-1",
      market: "Spread",
      side: "Suns +4.5",
      oddsDecimal: 1.95,
      stakeCash: 3500,
      stakeCredit: 0,
      placedAt: "2026-04-17T01:52:00Z",
      acceptedAt: "2026-04-17T01:55:00Z",
      status: "open",
    },
    {
      id: "tk-alpha-week",
      accountId: "acct-alpha",
      marketEventId: "evt-celtics-heat",
      ticketRef: "alpha-week-1",
      market: "Moneyline",
      side: "Celtics ML",
      oddsDecimal: 1.85,
      stakeCash: 1200,
      stakeCredit: 0,
      placedAt: "2026-04-15T01:05:00Z",
      acceptedAt: "2026-04-15T01:10:00Z",
      status: "settled",
    },
    {
      id: "tk-bravo-credit",
      accountId: "acct-bravo",
      marketEventId: "evt-lakers-warriors",
      ticketRef: "bravo-credit-1",
      market: "Player props",
      side: "Over 22.5 points",
      oddsDecimal: 1.75,
      stakeCash: 0,
      stakeCredit: 800,
      placedAt: "2026-04-06T02:25:00Z",
      acceptedAt: "2026-04-06T02:30:00Z",
      status: "settled",
    },
    {
      id: "tk-charlie-late",
      accountId: "acct-charlie",
      marketEventId: "evt-orioles-yankees",
      ticketRef: "charlie-late-1",
      market: "Moneyline",
      side: "Orioles ML",
      oddsDecimal: 2.15,
      stakeCash: 2500,
      stakeCredit: 0,
      placedAt: "2026-04-16T01:07:00Z",
      acceptedAt: "2026-04-16T01:10:00Z",
      status: "open",
    },
  ],
  ticketSettlements: [
    {
      id: "ts-alpha-win-final",
      ticketId: "tk-alpha-win",
      sourceOfEntry: "import",
      settlementType: "final",
      status: "posted",
      settledCashStake: 4000,
      settledCreditStake: 0,
      cashReturn: 7600,
      creditReturn: 0,
      pnlCash: 3600,
      pnlCredit: 0,
      effectiveAt: "2026-04-08T04:15:00Z",
      externalRef: "settle-alpha-win-1",
      payoutWalletEntryId: "we-alpha-payout-1",
    },
    {
      id: "ts-bravo-credit-final",
      ticketId: "tk-bravo-credit",
      sourceOfEntry: "import",
      settlementType: "final",
      status: "posted",
      settledCashStake: 0,
      settledCreditStake: 800,
      cashReturn: 600,
      creditReturn: 0,
      pnlCash: 600,
      pnlCredit: -800,
      effectiveAt: "2026-04-06T05:40:00Z",
      externalRef: "settle-bravo-credit-1",
      payoutWalletEntryId: "we-bravo-payout-1",
    },
    {
      id: "ts-alpha-week-final",
      ticketId: "tk-alpha-week",
      sourceOfEntry: "import",
      settlementType: "final",
      status: "posted",
      settledCashStake: 1200,
      settledCreditStake: 0,
      cashReturn: 2220,
      creditReturn: 0,
      pnlCash: 1020,
      pnlCredit: 0,
      effectiveAt: "2026-04-15T04:45:00Z",
      externalRef: "settle-alpha-week-1",
      payoutWalletEntryId: "we-alpha-payout-week",
    },
  ],
  payoutPeriods: [
    {
      id: "pp-weekly-prev",
      operatorId: "op-weekly-book",
      periodType: "weekly",
      periodStart: "2026-03-30",
      periodEnd: "2026-04-05",
      dueAt: "2026-04-10T17:00:00Z",
      status: "partially_paid",
    },
    {
      id: "pp-casino-mar",
      operatorId: "op-casino-monthly",
      periodType: "monthly",
      periodStart: "2026-03-01",
      periodEnd: "2026-03-31",
      dueAt: "2026-04-05T17:00:00Z",
      status: "disputed",
    },
    {
      id: "pp-weekly-current",
      operatorId: "op-weekly-book-2",
      periodType: "weekly",
      periodStart: "2026-04-13",
      periodEnd: "2026-04-19",
      dueAt: "2026-04-24T17:00:00Z",
      status: "open",
    },
  ],
  periodStatements: [
    {
      id: "stmt-alpha-prev",
      accountId: "acct-alpha",
      payoutPeriodId: "pp-weekly-prev",
      sourceOfEntry: "import",
      source: "operator_statement",
      status: "posted",
      statementSeriesId: "stmt-series-alpha-prev",
      versionNo: 1,
      authority: "authoritative",
      statementRef: "alpha-stmt-2026w14",
      expectedCashDue: 1800,
      expectedCreditDue: 0,
      postedAt: "2026-04-10T15:00:00Z",
      notes: "Operator posted short of expected; still collecting remaining 900",
    },
    {
      id: "stmt-bravo-mar-v1",
      accountId: "acct-bravo",
      payoutPeriodId: "pp-casino-mar",
      sourceOfEntry: "import",
      source: "operator_statement",
      status: "revised",
      statementSeriesId: "stmt-series-bravo-mar",
      versionNo: 1,
      authority: "superseded",
      supersededByStatementId: "stmt-bravo-mar-v2",
      statementRef: "bravo-stmt-2026-03-v1",
      expectedCashDue: 1700,
      expectedCreditDue: 900,
      postedAt: "2026-04-05T11:45:00Z",
      notes: "Original statement later replaced by revision.",
    },
    {
      id: "stmt-bravo-mar-v2",
      accountId: "acct-bravo",
      payoutPeriodId: "pp-casino-mar",
      sourceOfEntry: "import",
      source: "operator_statement",
      status: "disputed",
      statementSeriesId: "stmt-series-bravo-mar",
      versionNo: 2,
      authority: "suspended",
      supersedesStatementId: "stmt-bravo-mar-v1",
      statementRef: "bravo-stmt-2026-03-v2",
      expectedCashDue: 2000,
      expectedCreditDue: 1200,
      postedAt: "2026-04-06T09:00:00Z",
      notes: "Revised statement disputed; no authoritative statement until dispute resolves.",
    },
  ],
  creditGrants: [
    {
      id: "cg-bravo-1",
      accountId: "acct-bravo",
      issuedWalletEntryId: "we-bravo-credit-issue-2",
      grantRef: "bravo-credit-grant-1",
      originalAmount: 1200,
      expiresAt: "2026-04-30T23:59:59Z",
      rolloverRequirement: 1,
      status: "partially_wagered",
    },
  ],
  ticketCreditAllocations: [
    {
      id: "tca-bravo-1",
      ticketId: "tk-bravo-credit",
      creditGrantId: "cg-bravo-1",
      allocatedAmount: 800,
    },
  ],
  reconciliationRuns: [
    {
      id: "rr-alpha-prev",
      accountId: "acct-alpha",
      payoutPeriodId: "pp-weekly-prev",
      statementId: "stmt-alpha-prev",
      runType: "manual",
      status: "attention",
      runAt: "2026-04-17T17:00:00Z",
      completedAt: "2026-04-17T17:05:00Z",
      actor: "ops-user",
    },
    {
      id: "rr-bravo-mar",
      accountId: "acct-bravo",
      payoutPeriodId: "pp-casino-mar",
      statementId: "stmt-bravo-mar-v2",
      runType: "manual",
      status: "disputed",
      runAt: "2026-04-17T17:10:00Z",
      completedAt: "2026-04-17T17:20:00Z",
      actor: "ops-user",
    },
    {
      id: "rr-charlie-current",
      accountId: "acct-charlie",
      payoutPeriodId: "pp-weekly-current",
      runType: "manual",
      status: "blocked",
      runAt: "2026-04-17T17:25:00Z",
      completedAt: "2026-04-17T17:32:00Z",
      actor: "ops-user",
    },
  ],
  reconciliationIssues: [
    {
      id: "ri-alpha-duplicate",
      reconciliationRunId: "rr-alpha-prev",
      accountId: "acct-alpha",
      payoutPeriodId: "pp-weekly-prev",
      issueType: "duplicate_entry",
      severity: "medium",
      status: "open",
      amount: 10000,
      relatedEntityType: "wallet_entry",
      relatedEntityId: "we-alpha-dep-dup",
      openedAt: "2026-04-17T17:01:00Z",
      notes: "Duplicate deposit attempt shares external reference with posted deposit",
    },
    {
      id: "ri-alpha-shortfall",
      reconciliationRunId: "rr-alpha-prev",
      accountId: "acct-alpha",
      payoutPeriodId: "pp-weekly-prev",
      issueType: "statement_shortfall",
      severity: "high",
      status: "open",
      amount: 900,
      relatedEntityType: "statement",
      relatedEntityId: "stmt-alpha-prev",
      openedAt: "2026-04-17T17:02:00Z",
      notes: "Only half of statement cash due has been received",
    },
    {
      id: "ri-bravo-disputed",
      reconciliationRunId: "rr-bravo-mar",
      accountId: "acct-bravo",
      payoutPeriodId: "pp-casino-mar",
      issueType: "disputed_entry",
      severity: "high",
      status: "disputed",
      amount: 150,
      relatedEntityType: "wallet_entry",
      relatedEntityId: "we-bravo-adjustment-disputed",
      openedAt: "2026-04-17T17:12:00Z",
      notes: "Disputed manual deduction blocks clean reconciliation",
    },
    {
      id: "ri-bravo-shortfall",
      reconciliationRunId: "rr-bravo-mar",
      accountId: "acct-bravo",
      payoutPeriodId: "pp-casino-mar",
      issueType: "statement_shortfall",
      severity: "high",
      status: "open",
      amount: 0,
      relatedEntityType: "statement",
      relatedEntityId: "stmt-bravo-mar-v2",
      openedAt: "2026-04-17T17:13:00Z",
      notes: "Variance cannot be trusted until disputed revision is resolved; expected due is suspended.",
    },
    {
      id: "ri-bravo-variance",
      reconciliationRunId: "rr-bravo-mar",
      accountId: "acct-bravo",
      payoutPeriodId: "pp-casino-mar",
      issueType: "statement_shortfall",
      severity: "high",
      status: "open",
      amount: -2200,
      relatedEntityType: "statement",
      relatedEntityId: "stmt-bravo-mar-v2",
      openedAt: "2026-04-17T17:13:30Z",
      notes: "Ledger receipts total 1400 versus disputed revision expectation 3200.",
    },
    {
      id: "ri-charlie-missing-opening",
      reconciliationRunId: "rr-charlie-current",
      accountId: "acct-charlie",
      payoutPeriodId: "pp-weekly-current",
      issueType: "missing_opening_balance",
      severity: "high",
      status: "open",
      relatedEntityType: "account",
      relatedEntityId: "acct-charlie",
      openedAt: "2026-04-17T17:26:00Z",
      notes: "No opening balance entry exists, so cash balance is not authoritative",
    },
    {
      id: "ri-charlie-late",
      reconciliationRunId: "rr-charlie-current",
      accountId: "acct-charlie",
      payoutPeriodId: "pp-weekly-current",
      issueType: "late_settlement",
      severity: "high",
      status: "open",
      amount: 2500,
      relatedEntityType: "ticket",
      relatedEntityId: "tk-charlie-late",
      openedAt: "2026-04-17T17:27:00Z",
      notes: "Event is final but ticket remains open with no settlement event",
    },
    {
      id: "ri-charlie-deposit",
      reconciliationRunId: "rr-charlie-current",
      accountId: "acct-charlie",
      payoutPeriodId: "pp-weekly-current",
      issueType: "unmatched_deposit",
      severity: "medium",
      status: "open",
      amount: 4000,
      relatedEntityType: "wallet_entry",
      relatedEntityId: "we-charlie-dep-pending",
      openedAt: "2026-04-17T17:28:00Z",
      notes: "Pending deposit has no posted confirmation",
    },
  ],
  tasks: [
    {
      id: "task-alpha-claim",
      accountId: "acct-alpha",
      payoutPeriodId: "pp-weekly-prev",
      reconciliationIssueId: "ri-alpha-shortfall",
      taskType: "claim_payout",
      status: "open",
      priority: "high",
      title: "Collect remaining weekly payout for Alpha 07",
      dueAt: "2026-04-17T20:00:00Z",
      createdAt: "2026-04-17T17:03:00Z",
    },
    {
      id: "task-alpha-duplicate",
      accountId: "acct-alpha",
      payoutPeriodId: "pp-weekly-prev",
      reconciliationIssueId: "ri-alpha-duplicate",
      taskType: "resolve_duplicate",
      status: "open",
      priority: "medium",
      title: "Confirm duplicate deposit on Alpha 07 was not funded",
      dueAt: "2026-04-17T21:00:00Z",
      createdAt: "2026-04-17T17:04:00Z",
    },
    {
      id: "task-bravo-followup",
      accountId: "acct-bravo",
      payoutPeriodId: "pp-casino-mar",
      reconciliationIssueId: "ri-bravo-shortfall",
      noteId: "note-bravo-collections",
      taskType: "collections_followup",
      status: "in_progress",
      priority: "high",
      title: "Continue collections follow-up for Bravo 11 March statement",
      dueAt: "2026-04-17T19:00:00Z",
      createdAt: "2026-04-17T17:14:00Z",
    },
    {
      id: "task-charlie-ticket",
      accountId: "acct-charlie",
      payoutPeriodId: "pp-weekly-current",
      reconciliationIssueId: "ri-charlie-late",
      taskType: "investigate_ticket",
      status: "open",
      priority: "high",
      title: "Get settlement for Charlie 03 late ticket",
      dueAt: "2026-04-17T18:30:00Z",
      createdAt: "2026-04-17T17:29:00Z",
    },
    {
      id: "task-charlie-adjustment",
      accountId: "acct-alpha",
      reconciliationIssueId: "ri-alpha-duplicate",
      noteId: "note-alpha-adjustment",
      taskType: "review_adjustment",
      status: "done",
      priority: "low",
      title: "Review Alpha adjustment note",
      dueAt: "2026-04-17T16:00:00Z",
      createdAt: "2026-04-17T15:00:00Z",
      closedAt: "2026-04-17T15:30:00Z",
    },
  ],
  accountNotes: [
    {
      id: "note-alpha-adjustment",
      accountId: "acct-alpha",
      noteType: "internal",
      platform: "internal",
      subject: "Manual correction approved",
      body: "Manual +250 correction approved after checking counter-ticket ledger.",
      affectsCollections: false,
      affectsState: false,
      createdAt: "2026-04-12T17:28:00Z",
    },
    {
      id: "note-bravo-collections",
      accountId: "acct-bravo",
      noteType: "collections",
      platform: "telegram",
      subject: "March payout follow-up",
      body: "Operator acknowledged missing credit and asked for 24 more hours.",
      affectsCollections: true,
      affectsState: true,
      createdAt: "2026-04-17T12:10:00Z",
    },
    {
      id: "note-bravo-dispute",
      accountId: "acct-bravo",
      noteType: "payout_followup",
      platform: "whatsapp",
      subject: "Manual deduction disputed",
      body: "Asked operator to reverse 150 deduction and restate the month.",
      affectsCollections: true,
      affectsState: true,
      createdAt: "2026-04-07T09:20:00Z",
    },
  ],
  auditEvents: [
    {
      id: "ae-1",
      entityType: "wallet_entry",
      entityId: "we-alpha-adjustment-1",
      action: "manual_adjustment_logged",
      actor: "ops-user",
      createdAt: "2026-04-12T17:31:00Z",
      detail: "Manual adjustment recorded with approval note.",
    },
    {
      id: "ae-2",
      entityType: "wallet_entry",
      entityId: "we-alpha-dep-dup",
      action: "marked_duplicate",
      actor: "ops-user",
      createdAt: "2026-04-17T17:01:30Z",
      detail: "Duplicate deposit excluded from authoritative ledger.",
    },
    {
      id: "ae-3",
      entityType: "wallet_entry",
      entityId: "we-bravo-adjustment-disputed",
      action: "manual_adjustment_disputed",
      actor: "ops-user",
      createdAt: "2026-04-07T09:21:00Z",
      detail: "Manual deduction flagged as disputed pending operator response.",
    },
    {
      id: "ae-4",
      entityType: "statement",
      entityId: "stmt-bravo-mar-v2",
      action: "marked_disputed",
      actor: "ops-user",
      createdAt: "2026-04-17T17:12:30Z",
      detail: "Statement disputed pending operator response.",
    },
    {
      id: "ae-5",
      entityType: "ticket",
      entityId: "tk-charlie-late",
      action: "late_settlement_flagged",
      actor: "ops-user",
      createdAt: "2026-04-17T17:27:30Z",
      detail: "Event is final and ticket remains unsettled.",
    },
  ],
};
